language: node_js
node_js:
  - "node"
  - "iojs"
before_install: npm install -g grunt-cli codeclimate-test-reporter
after_script:
  - CODECLIMATE_REPO_TOKEN=fa5c14abafccec5e614f7aa0cc617a3168777b59c1b9034e2f69d18389e342f6 codeclimate-test-reporter < reports/coverage/lcov.info
